; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName        "XScreenSaverWin"
#define MyAppVersion     GetStringFileInfo('build\Release\xscreensaver.exe', "FileVersion")
#define MyAppCompanyName "Katayama Hirofumi MZ"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B7914227-CD94-4B6F-859C-E3823C9552DA}
AppName={#MyAppName}
AppVerName={#MyAppName} v{#MyAppName}
AppPublisher={#MyAppCompanyName}
AppPublisherURL=http://katahiromz.web.fc2.com/xscreensaverwin/eindex.html
AppSupportURL=http://katahiromz.web.fc2.com/xscreensaverwin/eindex.html
AppUpdatesURL=http://katahiromz.web.fc2.com/xscreensaverwin/eindex.html
DefaultDirName={pf}\XScreenSaver for Windows
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputBaseFilename=XScreenSaverWin-{#MyAppVersion}-Setup
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon={app}\xscreensaver.exe
LicenseFile=LICENSE.txt
VersionInfoVersion={#MyAppVersion}
OutputDir=.

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "README.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "READMEJP.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\Release\xscreensaver.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\Release\xscreensaver-text.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "gl-savers\starwars.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "gl-savers\starwars.txt"; DestDir: "{app}\starwars_scr"; Flags: ignoreversion
Source: "build\Release\abstractile.scr"; DestDir: "{app}\abstractile_scr"; Flags: ignoreversion
Source: "build\Release\anemone.scr"; DestDir: "{app}\anemone_scr"; Flags: ignoreversion
Source: "build\Release\anemotaxis.scr"; DestDir: "{app}\anemotaxis_scr"; Flags: ignoreversion
Source: "build\Release\antinspect.scr"; DestDir: "{app}\antinspect_scr"; Flags: ignoreversion
Source: "build\Release\antmaze.scr"; DestDir: "{app}\antmaze_scr"; Flags: ignoreversion
Source: "build\Release\antspotlight.scr"; DestDir: "{app}\antspotlight_scr"; Flags: ignoreversion
Source: "build\Release\apollonian.scr"; DestDir: "{app}\apollonian_scr"; Flags: ignoreversion
Source: "build\Release\atlantis.scr"; DestDir: "{app}\atlantis_scr"; Flags: ignoreversion
Source: "build\Release\attraction.scr"; DestDir: "{app}\attraction_scr"; Flags: ignoreversion
Source: "build\Release\atunnel.scr"; DestDir: "{app}\atunnel_scr"; Flags: ignoreversion
Source: "build\Release\barcode.scr"; DestDir: "{app}\barcode_scr"; Flags: ignoreversion
Source: "build\Release\blaster.scr"; DestDir: "{app}\blaster_scr"; Flags: ignoreversion
Source: "build\Release\blinkbox.scr"; DestDir: "{app}\blinkbox_scr"; Flags: ignoreversion
Source: "build\Release\blocktube.scr"; DestDir: "{app}\blocktube_scr"; Flags: ignoreversion
Source: "build\Release\boing.scr"; DestDir: "{app}\boing_scr"; Flags: ignoreversion
Source: "build\Release\bouboule.scr"; DestDir: "{app}\bouboule_scr"; Flags: ignoreversion
Source: "build\Release\bouncingcow.scr"; DestDir: "{app}\bouncingcow_scr"; Flags: ignoreversion
Source: "build\Release\boxed.scr"; DestDir: "{app}\boxed_scr"; Flags: ignoreversion
Source: "build\Release\braid.scr"; DestDir: "{app}\braid_scr"; Flags: ignoreversion
Source: "build\Release\bsod.scr"; DestDir: "{app}\bsod_scr"; Flags: ignoreversion
Source: "build\Release\bubble3d.scr"; DestDir: "{app}\bubble3d_scr"; Flags: ignoreversion
Source: "build\Release\bubbles.scr"; DestDir: "{app}\bubbles_scr"; Flags: ignoreversion
Source: "build\Release\bumps.scr"; DestDir: "{app}\bumps_scr"; Flags: ignoreversion
Source: "build\Release\cage.scr"; DestDir: "{app}\cage_scr"; Flags: ignoreversion
Source: "build\Release\carousel.scr"; DestDir: "{app}\carousel_scr"; Flags: ignoreversion
Source: "build\Release\ccurve.scr"; DestDir: "{app}\ccurve_scr"; Flags: ignoreversion
Source: "build\Release\celtic.scr"; DestDir: "{app}\celtic_scr"; Flags: ignoreversion
Source: "build\Release\circuit.scr"; DestDir: "{app}\circuit_scr"; Flags: ignoreversion
Source: "build\Release\cloudlife.scr"; DestDir: "{app}\cloudlife_scr"; Flags: ignoreversion
Source: "build\Release\companion.scr"; DestDir: "{app}\companion_scr"; Flags: ignoreversion
Source: "build\Release\compass.scr"; DestDir: "{app}\compass_scr"; Flags: ignoreversion
Source: "build\Release\coral.scr"; DestDir: "{app}\coral_scr"; Flags: ignoreversion
Source: "build\Release\crackberg.scr"; DestDir: "{app}\crackberg_scr"; Flags: ignoreversion
Source: "build\Release\critical.scr"; DestDir: "{app}\critical_scr"; Flags: ignoreversion
Source: "build\Release\crystal.scr"; DestDir: "{app}\crystal_scr"; Flags: ignoreversion
Source: "build\Release\cube21.scr"; DestDir: "{app}\cube21_scr"; Flags: ignoreversion
Source: "build\Release\cubenetic.scr"; DestDir: "{app}\cubenetic_scr"; Flags: ignoreversion
Source: "build\Release\cubestorm.scr"; DestDir: "{app}\cubestorm_scr"; Flags: ignoreversion
Source: "build\Release\cubicgrid.scr"; DestDir: "{app}\cubicgrid_scr"; Flags: ignoreversion
Source: "build\Release\cwaves.scr"; DestDir: "{app}\cwaves_scr"; Flags: ignoreversion
Source: "build\Release\cynosure.scr"; DestDir: "{app}\cynosure_scr"; Flags: ignoreversion
Source: "build\Release\dangerball.scr"; DestDir: "{app}\dangerball_scr"; Flags: ignoreversion
Source: "build\Release\decayscreen.scr"; DestDir: "{app}\decayscreen_scr"; Flags: ignoreversion
Source: "build\Release\deco.scr"; DestDir: "{app}\deco_scr"; Flags: ignoreversion
Source: "build\Release\deluxe.scr"; DestDir: "{app}\deluxe_scr"; Flags: ignoreversion
Source: "build\Release\demon.scr"; DestDir: "{app}\demon_scr"; Flags: ignoreversion
Source: "build\Release\discrete.scr"; DestDir: "{app}\discrete_scr"; Flags: ignoreversion
Source: "build\Release\distort.scr"; DestDir: "{app}\distort_scr"; Flags: ignoreversion
Source: "build\Release\dnalogo.scr"; DestDir: "{app}\dnalogo_scr"; Flags: ignoreversion
Source: "build\Release\drift.scr"; DestDir: "{app}\drift_scr"; Flags: ignoreversion
Source: "build\Release\endgame.scr"; DestDir: "{app}\endgame_scr"; Flags: ignoreversion
Source: "build\Release\engine.scr"; DestDir: "{app}\engine_scr"; Flags: ignoreversion
Source: "build\Release\epicycle.scr"; DestDir: "{app}\epicycle_scr"; Flags: ignoreversion
Source: "build\Release\eruption.scr"; DestDir: "{app}\eruption_scr"; Flags: ignoreversion
Source: "build\Release\euler2d.scr"; DestDir: "{app}\euler2d_scr"; Flags: ignoreversion
Source: "build\Release\extrusion.scr"; DestDir: "{app}\extrusion_scr"; Flags: ignoreversion
Source: "build\Release\fadeplot.scr"; DestDir: "{app}\fadeplot_scr"; Flags: ignoreversion
Source: "build\Release\fiberlamp.scr"; DestDir: "{app}\fiberlamp_scr"; Flags: ignoreversion
Source: "build\Release\fireworkx.scr"; DestDir: "{app}\fireworkx_scr"; Flags: ignoreversion
Source: "build\Release\flame.scr"; DestDir: "{app}\flame_scr"; Flags: ignoreversion
Source: "build\Release\flipflop.scr"; DestDir: "{app}\flipflop_scr"; Flags: ignoreversion
Source: "build\Release\flipscreen3d.scr"; DestDir: "{app}\flipscreen3d_scr"; Flags: ignoreversion
Source: "build\Release\fliptext.scr"; DestDir: "{app}\fliptext_scr"; Flags: ignoreversion
Source: "build\Release\flow.scr"; DestDir: "{app}\flow_scr"; Flags: ignoreversion
Source: "build\Release\fluidballs.scr"; DestDir: "{app}\fluidballs_scr"; Flags: ignoreversion
Source: "build\Release\flurry.scr"; DestDir: "{app}\flurry_scr"; Flags: ignoreversion
Source: "build\Release\flyingtoasters.scr"; DestDir: "{app}\flyingtoasters_scr"; Flags: ignoreversion
Source: "build\Release\fontglide.scr"; DestDir: "{app}\fontglide_scr"; Flags: ignoreversion
Source: "build\Release\forest.scr"; DestDir: "{app}\forest_scr"; Flags: ignoreversion
Source: "build\Release\fuzzyflakes.scr"; DestDir: "{app}\fuzzyflakes_scr"; Flags: ignoreversion
Source: "build\Release\galaxy.scr"; DestDir: "{app}\galaxy_scr"; Flags: ignoreversion
Source: "build\Release\gears.scr"; DestDir: "{app}\gears_scr"; Flags: ignoreversion
Source: "build\Release\gflux.scr"; DestDir: "{app}\gflux_scr"; Flags: ignoreversion
Source: "build\Release\glblur.scr"; DestDir: "{app}\glblur_scr"; Flags: ignoreversion
Source: "build\Release\glcells.scr"; DestDir: "{app}\glcells_scr"; Flags: ignoreversion
Source: "build\Release\gleidescope.scr"; DestDir: "{app}\gleidescope_scr"; Flags: ignoreversion
Source: "build\Release\glforestfire.scr"; DestDir: "{app}\glforestfire_scr"; Flags: ignoreversion
Source: "build\Release\glhanoi.scr"; DestDir: "{app}\glhanoi_scr"; Flags: ignoreversion
Source: "build\Release\glknots.scr"; DestDir: "{app}\glknots_scr"; Flags: ignoreversion
Source: "build\Release\glmatrix.scr"; DestDir: "{app}\glmatrix_scr"; Flags: ignoreversion
Source: "build\Release\glplanet.scr"; DestDir: "{app}\glplanet_scr"; Flags: ignoreversion
Source: "build\Release\glschool.scr"; DestDir: "{app}\glschool_scr"; Flags: ignoreversion
Source: "build\Release\glslideshow.scr"; DestDir: "{app}\glslideshow_scr"; Flags: ignoreversion
Source: "build\Release\glsnake.scr"; DestDir: "{app}\glsnake_scr"; Flags: ignoreversion
Source: "build\Release\gltext.scr"; DestDir: "{app}\gltext_scr"; Flags: ignoreversion
Source: "build\Release\goop.scr"; DestDir: "{app}\goop_scr"; Flags: ignoreversion
Source: "build\Release\grav.scr"; DestDir: "{app}\grav_scr"; Flags: ignoreversion
Source: "build\Release\greynetic.scr"; DestDir: "{app}\greynetic_scr"; Flags: ignoreversion
Source: "build\Release\halftone.scr"; DestDir: "{app}\halftone_scr"; Flags: ignoreversion
Source: "build\Release\halo.scr"; DestDir: "{app}\halo_scr"; Flags: ignoreversion
Source: "build\Release\helix.scr"; DestDir: "{app}\helix_scr"; Flags: ignoreversion
Source: "build\Release\hexadrop.scr"; DestDir: "{app}\hexadrop_scr"; Flags: ignoreversion
Source: "build\Release\hilbert.scr"; DestDir: "{app}\hilbert_scr"; Flags: ignoreversion
Source: "build\Release\hopalong.scr"; DestDir: "{app}\hopalong_scr"; Flags: ignoreversion
Source: "build\Release\hyperball.scr"; DestDir: "{app}\hyperball_scr"; Flags: ignoreversion
Source: "build\Release\hypercube.scr"; DestDir: "{app}\hypercube_scr"; Flags: ignoreversion
Source: "build\Release\hypertorus.scr"; DestDir: "{app}\hypertorus_scr"; Flags: ignoreversion
Source: "build\Release\hypnowheel.scr"; DestDir: "{app}\hypnowheel_scr"; Flags: ignoreversion
Source: "build\Release\ifs.scr"; DestDir: "{app}\ifs_scr"; Flags: ignoreversion
Source: "build\Release\imsmap.scr"; DestDir: "{app}\imsmap_scr"; Flags: ignoreversion
Source: "build\Release\interaggregate.scr"; DestDir: "{app}\interaggregate_scr"; Flags: ignoreversion
Source: "build\Release\interference.scr"; DestDir: "{app}\interference_scr"; Flags: ignoreversion
Source: "build\Release\intermomentary.scr"; DestDir: "{app}\intermomentary_scr"; Flags: ignoreversion
Source: "build\Release\jigglypuff.scr"; DestDir: "{app}\jigglypuff_scr"; Flags: ignoreversion
Source: "build\Release\jigsaw.scr"; DestDir: "{app}\jigsaw_scr"; Flags: ignoreversion
Source: "build\Release\julia.scr"; DestDir: "{app}\julia_scr"; Flags: ignoreversion
Source: "build\Release\juggle.scr"; DestDir: "{app}\juggle_scr"; Flags: ignoreversion
Source: "build\Release\juggler3d.scr"; DestDir: "{app}\juggler3d_scr"; Flags: ignoreversion
Source: "build\Release\kaleidescope.scr"; DestDir: "{app}\kaleidescope_scr"; Flags: ignoreversion
Source: "build\Release\kaleidocycle.scr"; DestDir: "{app}\kaleidocycle_scr"; Flags: ignoreversion
Source: "build\Release\klein.scr"; DestDir: "{app}\klein_scr"; Flags: ignoreversion
Source: "build\Release\kumppa.scr"; DestDir: "{app}\kumppa_scr"; Flags: ignoreversion
Source: "build\Release\lament.scr"; DestDir: "{app}\lament_scr"; Flags: ignoreversion
Source: "build\Release\laser.scr"; DestDir: "{app}\laser_scr"; Flags: ignoreversion
Source: "build\Release\lavalite.scr"; DestDir: "{app}\lavalite_scr"; Flags: ignoreversion
Source: "build\Release\lcdscrub.scr"; DestDir: "{app}\lcdscrub_scr"; Flags: ignoreversion
Source: "build\Release\lightning.scr"; DestDir: "{app}\lightning_scr"; Flags: ignoreversion
Source: "build\Release\lisa.scr"; DestDir: "{app}\lisa_scr"; Flags: ignoreversion
Source: "build\Release\lissie.scr"; DestDir: "{app}\lissie_scr"; Flags: ignoreversion
Source: "build\Release\lmorph.scr"; DestDir: "{app}\lmorph_scr"; Flags: ignoreversion
Source: "build\Release\lockward.scr"; DestDir: "{app}\lockward_scr"; Flags: ignoreversion
Source: "build\Release\loop.scr"; DestDir: "{app}\loop_scr"; Flags: ignoreversion
Source: "build\Release\m6502.scr"; DestDir: "{app}\m6502_scr"; Flags: ignoreversion
Source: "build\Release\maze.scr"; DestDir: "{app}\maze_scr"; Flags: ignoreversion
Source: "build\Release\memscroller.scr"; DestDir: "{app}\memscroller_scr"; Flags: ignoreversion
Source: "build\Release\menger.scr"; DestDir: "{app}\menger_scr"; Flags: ignoreversion
Source: "build\Release\metaballs.scr"; DestDir: "{app}\metaballs_scr"; Flags: ignoreversion
Source: "build\Release\mirrorblob.scr"; DestDir: "{app}\mirrorblob_scr"; Flags: ignoreversion
Source: "build\Release\moebiusgears.scr"; DestDir: "{app}\moebiusgears_scr"; Flags: ignoreversion
Source: "build\Release\moebius.scr"; DestDir: "{app}\moebius_scr"; Flags: ignoreversion
Source: "build\Release\moire.scr"; DestDir: "{app}\moire_scr"; Flags: ignoreversion
Source: "build\Release\molecule.scr"; DestDir: "{app}\molecule_scr"; Flags: ignoreversion
Source: "build\Release\morph3d.scr"; DestDir: "{app}\morph3d_scr"; Flags: ignoreversion
Source: "build\Release\mountain.scr"; DestDir: "{app}\mountain_scr"; Flags: ignoreversion
Source: "build\Release\munch.scr"; DestDir: "{app}\munch_scr"; Flags: ignoreversion
Source: "build\Release\nerverot.scr"; DestDir: "{app}\nerverot_scr"; Flags: ignoreversion
Source: "build\Release\noof.scr"; DestDir: "{app}\noof_scr"; Flags: ignoreversion
Source: "build\Release\noseguy.scr"; DestDir: "{app}\noseguy_scr"; Flags: ignoreversion
Source: "build\Release\pacman.scr"; DestDir: "{app}\pacman_scr"; Flags: ignoreversion
Source: "build\Release\pedal.scr"; DestDir: "{app}\pedal_scr"; Flags: ignoreversion
Source: "build\Release\piecewise.scr"; DestDir: "{app}\piecewise_scr"; Flags: ignoreversion
Source: "build\Release\penetrate.scr"; DestDir: "{app}\penetrate_scr"; Flags: ignoreversion
Source: "build\Release\penrose.scr"; DestDir: "{app}\penrose_scr"; Flags: ignoreversion
Source: "build\Release\petri.scr"; DestDir: "{app}\petri_scr"; Flags: ignoreversion
Source: "build\Release\photopile.scr"; DestDir: "{app}\photopile_scr"; Flags: ignoreversion
Source: "build\Release\phosphor.scr"; DestDir: "{app}\phosphor_scr"; Flags: ignoreversion
Source: "build\Release\pinion.scr"; DestDir: "{app}\pinion_scr"; Flags: ignoreversion
Source: "build\Release\pipes.scr"; DestDir: "{app}\pipes_scr"; Flags: ignoreversion
Source: "build\Release\polyhedra.scr"; DestDir: "{app}\polyhedra_scr"; Flags: ignoreversion
Source: "build\Release\polyominoes.scr"; DestDir: "{app}\polyominoes_scr"; Flags: ignoreversion
Source: "build\Release\polytopes.scr"; DestDir: "{app}\polytopes_scr"; Flags: ignoreversion
Source: "build\Release\pong.scr"; DestDir: "{app}\pong_scr"; Flags: ignoreversion
Source: "build\Release\popsquares.scr"; DestDir: "{app}\popsquares_scr"; Flags: ignoreversion
Source: "build\Release\providence.scr"; DestDir: "{app}\providence_scr"; Flags: ignoreversion
Source: "build\Release\pulsar.scr"; DestDir: "{app}\pulsar_scr"; Flags: ignoreversion
Source: "build\Release\pyro.scr"; DestDir: "{app}\pyro_scr"; Flags: ignoreversion
Source: "build\Release\quasicrystal.scr"; DestDir: "{app}\quasicrystal_scr"; Flags: ignoreversion
Source: "build\Release\queens.scr"; DestDir: "{app}\queens_scr"; Flags: ignoreversion
Source: "build\Release\random.scr"; DestDir: "{app}\random_scr"; Flags: ignoreversion
Source: "build\Release\rd-bomb.scr"; DestDir: "{app}\rd-bomb_scr"; Flags: ignoreversion
Source: "build\Release\ripples.scr"; DestDir: "{app}\ripples_scr"; Flags: ignoreversion
Source: "build\Release\rocks.scr"; DestDir: "{app}\rocks_scr"; Flags: ignoreversion
Source: "build\Release\rorschach.scr"; DestDir: "{app}\rorschach_scr"; Flags: ignoreversion
Source: "build\Release\rotor.scr"; DestDir: "{app}\rotor_scr"; Flags: ignoreversion
Source: "build\Release\rotzoomer.scr"; DestDir: "{app}\rotzoomer_scr"; Flags: ignoreversion
Source: "build\Release\rubikblocks.scr"; DestDir: "{app}\rubikblocks_scr"; Flags: ignoreversion
Source: "build\Release\rubik.scr"; DestDir: "{app}\rubik_scr"; Flags: ignoreversion
Source: "build\Release\sballs.scr"; DestDir: "{app}\sballs_scr"; Flags: ignoreversion
Source: "build\Release\shadebobs.scr"; DestDir: "{app}\shadebobs_scr"; Flags: ignoreversion
Source: "build\Release\sierpinski3d.scr"; DestDir: "{app}\sierpinski3d_scr"; Flags: ignoreversion
Source: "build\Release\sierpinski.scr"; DestDir: "{app}\sierpinski_scr"; Flags: ignoreversion
Source: "build\Release\skytentacles.scr"; DestDir: "{app}\skytentacles_scr"; Flags: ignoreversion
Source: "build\Release\slidescreen.scr"; DestDir: "{app}\slidescreen_scr"; Flags: ignoreversion
Source: "build\Release\slip.scr"; DestDir: "{app}\slip_scr"; Flags: ignoreversion
Source: "build\Release\sonar.scr"; DestDir: "{app}\sonar_scr"; Flags: ignoreversion
Source: "build\Release\speedmine.scr"; DestDir: "{app}\speedmine_scr"; Flags: ignoreversion
Source: "build\Release\spheremonics.scr"; DestDir: "{app}\spheremonics_scr"; Flags: ignoreversion
Source: "build\Release\sphere.scr"; DestDir: "{app}\sphere_scr"; Flags: ignoreversion
Source: "build\Release\spiral.scr"; DestDir: "{app}\spiral_scr"; Flags: ignoreversion
Source: "build\Release\spotlight.scr"; DestDir: "{app}\spotlight_scr"; Flags: ignoreversion
Source: "build\Release\sproingies.scr"; DestDir: "{app}\sproingies_scr"; Flags: ignoreversion
Source: "build\Release\squiral.scr"; DestDir: "{app}\squiral_scr"; Flags: ignoreversion
Source: "build\Release\stairs.scr"; DestDir: "{app}\stairs_scr"; Flags: ignoreversion
Source: "build\Release\starfish.scr"; DestDir: "{app}\starfish_scr"; Flags: ignoreversion
Source: "build\Release\starwars.scr"; DestDir: "{app}\starwars_scr"; Flags: ignoreversion
Source: "build\Release\stonerview.scr"; DestDir: "{app}\stonerview_scr"; Flags: ignoreversion
Source: "build\Release\strange.scr"; DestDir: "{app}\strange_scr"; Flags: ignoreversion
Source: "build\Release\substrate.scr"; DestDir: "{app}\substrate_scr"; Flags: ignoreversion
Source: "build\Release\superquadrics.scr"; DestDir: "{app}\superquadrics_scr"; Flags: ignoreversion
Source: "build\Release\surfaces.scr"; DestDir: "{app}\surfaces_scr"; Flags: ignoreversion
Source: "build\Release\swirl.scr"; DestDir: "{app}\swirl_scr"; Flags: ignoreversion
Source: "build\Release\tangram.scr"; DestDir: "{app}\tangram_scr"; Flags: ignoreversion
Source: "build\Release\thornbird.scr"; DestDir: "{app}\thornbird_scr"; Flags: ignoreversion
Source: "build\Release\topblock.scr"; DestDir: "{app}\topblock_scr"; Flags: ignoreversion
Source: "build\Release\triangle.scr"; DestDir: "{app}\triangle_scr"; Flags: ignoreversion
Source: "build\Release\tronbit.scr"; DestDir: "{app}\tronbit_scr"; Flags: ignoreversion
Source: "build\Release\truchet.scr"; DestDir: "{app}\truchet_scr"; Flags: ignoreversion
Source: "build\Release\twang.scr"; DestDir: "{app}\twang_scr"; Flags: ignoreversion
Source: "build\Release\unknownpleasures.scr"; DestDir: "{app}\unknownpleasures_scr"; Flags: ignoreversion
Source: "build\Release\vermiculate.scr"; DestDir: "{app}\vermiculate_scr"; Flags: ignoreversion
Source: "build\Release\vines.scr"; DestDir: "{app}\vines_scr"; Flags: ignoreversion
Source: "build\Release\voronoi.scr"; DestDir: "{app}\voronoi_scr"; Flags: ignoreversion
Source: "build\Release\wander.scr"; DestDir: "{app}\wander_scr"; Flags: ignoreversion
Source: "build\Release\whirlwindwarp.scr"; DestDir: "{app}\whirlwindwarp_scr"; Flags: ignoreversion
Source: "build\Release\whirlygig.scr"; DestDir: "{app}\whirlygig_scr"; Flags: ignoreversion
Source: "build\Release\worm.scr"; DestDir: "{app}\worm_scr"; Flags: ignoreversion
Source: "build\Release\wormhole.scr"; DestDir: "{app}\wormhole_scr"; Flags: ignoreversion
Source: "build\Release\xanalogtv.scr"; DestDir: "{app}\xanalogtv_scr"; Flags: ignoreversion
Source: "build\Release\xflame.scr"; DestDir: "{app}\xflame_scr"; Flags: ignoreversion
Source: "build\Release\xjack.scr"; DestDir: "{app}\xjack_scr"; Flags: ignoreversion
Source: "build\Release\xlyap.scr"; DestDir: "{app}\xlyap_scr"; Flags: ignoreversion
Source: "build\Release\xmatrix.scr"; DestDir: "{app}\xmatrix_scr"; Flags: ignoreversion
Source: "build\Release\xrayswarm.scr"; DestDir: "{app}\xrayswarm_scr"; Flags: ignoreversion
Source: "build\Release\xspirograph.scr"; DestDir: "{app}\xspirograph_scr"; Flags: ignoreversion
Source: "build\Release\zoom.scr"; DestDir: "{app}\zoom_scr"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\xscreensaver.exe"
Name: "{group}\README.txt"; Filename: "{app}\README.txt"
Name: "{group}\READMEJP.txt"; Filename: "{app}\READMEJP.txt"
Name: "{group}\CHANGELOG.txt"; Filename: "{app}\CHANGELOG.txt"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "http://katahiromz.web.fc2.com/xscreensaverwin/eindex.html"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\xscreensaver.exe"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ"; Flags: uninsdeletekeyifempty
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Abstractile"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Anemone"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Anemotaxis"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Ant"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\AntInspect"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\AntMaze"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\AntSpotlight"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Apollonian"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Apple2"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Atlantis"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Attraction"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Atunnel"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Barcode"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Blaster"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\BlinkBox"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\BlitSpin"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\BlockTube"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Boing"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Bouboule"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\BouncingCow"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\BoxFit"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Boxed"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Braid"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\BSOD"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Bubble3D"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Bubbles"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Bumps"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\CCurve"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\CWaves"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Cage"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Carousel"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Celtic"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Circuit"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\CloudLife"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\CompanionCube"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Compass"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Coral"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Crackberg"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Critical"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Crystal"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Cube21"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\CubeStorm"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Cubenetic"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\CubicGrid"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Cynosure"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\DNALogo"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\DangerBall"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\DecayScreen"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Deco"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Deluxe"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Demon"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Discrete"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Distort"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Drift"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Endgame"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Engine"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Epicycle"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Eruption"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Euler2D"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Extrusion"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FadePlot"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Fiberlamp"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Fireworkx"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Flag"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Flame"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FlipFlop"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FlipScreen3D"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FlipText"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Flow"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FluidBalls"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Flurry"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FlyingToasters"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FontGlide"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Forest"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\FuzzyFlakes"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GFlux"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLBlur"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLCells"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLForestFire"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLHanoi"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLKnots"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLMatrix"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLPlanet"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLSchool"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLSlideshow"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLSnake"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\GLText"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Galaxy"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Gears"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Gleidescope"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Goop"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Grav"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Greynetic"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Halftone"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Halo"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Helix"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Hexadrop"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Hilbert"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Hopalong"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\HyperBall"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\HyperCube"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Hypertorus"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Hypnowheel"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\IFS"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\IMSMap"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Interaggregate"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Interference"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Intermomentary"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\JigglyPuff"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Jigsaw"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Juggle"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Juggler3D"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Julia"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Kaleidescope"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Kaleidocycle"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Klein"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Kumppa"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\LCDscrub"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\LMorph"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Lament"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Laser"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Lavalite"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Lightning"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Lisa"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Lissie"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Lockward"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Loop"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\m6502"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Maze"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\MemScroller"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Menger"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\MetaBalls"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\MirrorBlob"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Moebius"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\MoebiusGears"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Moire"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Moire2"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Molecule"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Morph3D"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Mountain"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Munch"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\NerveRot"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Noof"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\NoseGuy"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Pacman"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Pedal"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Penetrate"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Penrose"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Petri"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Phosphor"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Photopile"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Piecewise"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Pinion"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Pipes"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Polyhedra"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Polyominoes"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Polytopes"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Pong"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\PopSquares"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Providence"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Pulsar"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Pyro"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Qix"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\QuasiCrystal"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Queens"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\RDbomb"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Ripples"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Rocks"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Rorschach"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\RotZoomer"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Rotor"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Rubik"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\RubikBlocks"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\SBalls"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\ShadeBobs"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Sierpinski"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Sierpinski3D"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\SkyTentacles"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Slip"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\SlideScreen"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Sonar"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\SpeedMine"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Sphere"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Spheremonics"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Spiral"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Spotlight"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Sproingies"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Squiral"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Stairs"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\StarWars"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Starfish"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\StonerView"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Strange"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Substrate"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Superquadrics"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Surfaces"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Swirl"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\T3D"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Tangram"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Thornbird"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\TimeTunnel"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\TopBlock"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Triangle"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\TronBit"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Truchet"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Twang"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\UnknownPleasures"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Vermiculate"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Vines"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Voronoi"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Wander"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\WhirlWindWarp"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Whirlygig"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Worm"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Wormhole"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\XAnalogTV"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\XFlame"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\XJack"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\XLyap"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\XMatrix"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\XRaySwarm"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\XSpirograph"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\Zoom"; Flags: uninsdeletekey

[Run]
Filename: "{app}\xscreensaver.exe"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent
