//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 6.0.7.
// xscreensaver_res.rc

#define IDC_MYICON                          2
#define IDC_XSCREENSAVER                    109

#define IDD_XSCREENSAVER_DIALOG             102
#define IDD_ABOUTBOX                        103

#define IDI_XSCREENSAVER                    107
#define IDI_SMALL                           108

#define IDM_ABOUT                           104
#define IDM_EXIT                            105

#define IDR_MAINFRAME                       128

#define IDS_APP_TITLE                       103

#define ID_INSTALL                          110
#define ID_CONFIGURE                        111
#define ID_COMBO                            112
#define ID_PREVIEW                          113
#define ID_TEST                             114

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    129
        #define _APS_NEXT_COMMAND_VALUE     115
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
